[package]
name = "aoc_2020"
version = "0.1.0"
authors = ["The0x539 <the0x539@gmail.com>"]
edition = "2018"

[lib]
name = "aoc_2020"
path = "src/lib.rs"

[[bin]]
name = "aoc_2020"
path = "src/main.rs"

[dependencies]
itertools = "0.9.0"
regex = "1.4.2"
